### ISSUE TITLE
关于Focal loss计算

### ISSUE THREAD

**Issue by MrHwc** [610265158/mobilenetv3_centernet#7]
作者，你好。Focal loss代码部分，hm_target被放大到了[0, 255]，pred_hm是经过sigmoid输出的，范围应该在[0, 1]。将hm_target、hm_target直接计算Focal loss是否有误？我将hm_target改为 [0, 1] 再计算Focal loss，测试的AP比hm_target范围[0, 255]结果要低一点。

**Comment by 610265158** [comment]
Hi，
hm_target被放大到了[0, 255]， 是为了省内存和减少io，可以以uint8 存储，在训练时候，做了恢复到0-1的处理，这块不需要动

**Comment by MrHwc** [comment]
多谢解答，是我没注意到`process_label`
